### ISSUE TITLE
Need info in readme or wiki about capistrano keys

### ISSUE THREAD

**Issue by mark-dce** [acozine/sufia-centos#11]
The current scripts point to key's in Alicia's personal repo - see 
https://github.com/acozine/sufia-centos/blob/master/roles/housekeeping/tasks/users_groups_dirs.yml#L28-L31

``` yaml
- name: add keys for capistrano user
  authorized_key: user={{ capistrano_user }} key="{{ item }}" 
  with_items:
      - https://github.com/acozine.keys
```
