### ISSUE TITLE
use ansible multiline format instead of \ for line continuation

### ISSUE THREAD

**Issue by acozine** [acozine/sufia-centos#62]
I find that this format:

```
module:
  first_parameter: string
  second_parameter: some_long_string_with_{{ a_variable }} 
  third_parameter: some_other_string
```

makes the scripts easier to read than this format:

```
module: first_parameter=string second_parameter=some_long_string_with_{{ a_variable }} \
third_parameter=some_other_string
```
